"""agent record table

Revision ID: 22513120afef
Revises: 373c8b07dccb
Create Date: 2023-11-17 07:34:56.705730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22513120afef"
down_revision: Union[str, None] = "373c8b07dccb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_record",
        sa.Column("agent_uid", sa.UUID(), nullable=False),
        sa.Column("admin_uid", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("last_survey_update", sa.DateTime(), nullable=True),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("agent_uid"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_agent_record_admin_uid"), "agent_record", ["admin_uid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_record_admin_uid"), table_name="agent_record")
    op.drop_table("agent_record")
    # ### end Alembic commands ###
